#!/usr/bin/env python3
"""
PublicForward/ForVPS/vps_server.py — Enhanced VPS Bridge (FastAPI + WebSocket).

Exposes an OpenAI-compatible REST API (/v1/chat/completions, /v1/models) and
bridges requests over WebSocket to one or more local workers (public.py),
each of which drives a pool of real DeepSeek browsers.

NEW FEATURES:
  1. CORS middleware
  2. Worker ID generated by VPS (not from worker)
  3. Worker wait timeout (queue requests with timeout)
  4. update_accounts from worker (runtime account updates)
  5. /v1/models show live accounts from workers
  6. X-Session-ID response header
  7. X-Account-Name + X-Conversation-URL headers
  8. think_mode field (DeepSeek alias)
  9. Attachment with "filename"+"data"+"mime_type"
  10. finish_reason + tool_calls response path (OpenAI-compatible)
  11. x_meta block in response (session, account, timing, conversation_url)
  12. Worker stats detail in /health and /
  13. reject_future() when worker sends error message

Run:
  python vps_server.py --port 8000 --token MY_SHARED_SECRET
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import time
import uuid
from contextlib import asynccontextmanager
from typing import Any, AsyncGenerator, Optional

from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect, HTTPException
from fastapi.responses import JSONResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import uvicorn


# =========================================================================== #
# Config (env / CLI)
# =========================================================================== #
AUTH_TOKEN = os.environ.get("PAF_TOKEN", "change-me")
REQUEST_TIMEOUT = float(os.environ.get("PAF_REQUEST_TIMEOUT", "330"))
WORKER_WAIT_TIMEOUT = float(os.environ.get("WORKER_WAIT_TIMEOUT", "60"))

# Feature 8: think_mode aliases (DeepSeek-specific)
THINK_MODE_ALIASES = {
    "auto": {"model_tab": "instant", "deep_think": False, "web_search": False},
    "instant": {"model_tab": "instant", "deep_think": False, "web_search": False},
    "thinking": {"model_tab": "expert", "deep_think": True, "web_search": False},
    "expert": {"model_tab": "expert", "deep_think": True, "web_search": False},
    "reasoning": {"model_tab": "expert", "deep_think": True, "web_search": False},
    "fast": {"model_tab": "instant", "deep_think": False, "web_search": False},
    "vision": {"model_tab": "vision", "deep_think": False, "web_search": False},
}

MODEL_ALIASES = {
    # OpenAI-style model id -> (model_tab, deep_think)
    "deepseek-chat": {"model_tab": "instant", "deep_think": False},
    "deepseek-reasoner": {"model_tab": "expert", "deep_think": True},
    "deepseek-vision": {"model_tab": "vision", "deep_think": False},
}


# =========================================================================== #
# Pydantic models — OpenAI Chat Completions schema
# =========================================================================== #
class ChatMessage(BaseModel):
    role: str
    content: Any  # str, or list of content parts (for multimodal)
    name: Optional[str] = None


class ToolFunctionDef(BaseModel):
    name: str
    description: Optional[str] = None
    parameters: Optional[dict] = None


class Tool(BaseModel):
    type: str = "function"
    function: ToolFunctionDef


class AttachmentPayload(BaseModel):
    """Feature 9: Enhanced attachment with filename + data + mime_type."""

    filename: str
    data: str  # base64-encoded
    mime_type: str


class ChatCompletionRequest(BaseModel):
    model: str = "deepseek-chat"
    messages: list[ChatMessage]
    stream: bool = False
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    tools: Optional[list[Tool]] = None
    # Custom DeepSeek extensions:
    deep_think: Optional[bool] = None
    web_search: Optional[bool] = None
    model_tab: Optional[str] = None
    session_id: Optional[str] = None
    mode: Optional[str] = None  # "new" | "continue"
    attachments: Optional[list[AttachmentPayload]] = None
    # Feature 8: think_mode alias
    think_mode: Optional[str] = None
    # Feature 4: preferred_account routing
    preferred_account: Optional[str] = None

    def last_user_message(self) -> str:
        for msg in reversed(self.messages):
            if msg.role == "user":
                if isinstance(msg.content, str):
                    return msg.content
                if isinstance(msg.content, list):
                    parts = [
                        p.get("text", "")
                        for p in msg.content
                        if isinstance(p, dict) and p.get("type") == "text"
                    ]
                    return "\n".join(parts)
        return ""


# Rebuild models
for _m in (ChatMessage, ToolFunctionDef, Tool, AttachmentPayload, ChatCompletionRequest):
    _m.model_rebuild()


# =========================================================================== #
# Helpers
# =========================================================================== #
def _token_estimate(text: str) -> int:
    if not text:
        return 0
    return max(1, len(text) // 4)


def _make_id() -> str:
    return f"chatcmpl-{uuid.uuid4().hex[:24]}"


def _resolve_think_mode(req: ChatCompletionRequest) -> dict:
    """Feature 8: Resolve think_mode to DeepSeek parameters."""
    if req.think_mode:
        alias = THINK_MODE_ALIASES.get(req.think_mode.lower())
        if alias:
            return alias
    return {}


# =========================================================================== #
# WorkerManager
# =========================================================================== #
class WorkerEntry:
    def __init__(
        self, worker_id: str, ws: WebSocket, max_concurrent: int, accounts: list[str]
    ) -> None:
        self.worker_id = worker_id
        self.ws = ws
        self.max_concurrent = max_concurrent
        self.accounts = accounts
        self.in_flight = 0
        self.connected_at = time.time()
        self.last_ping = time.time()


class WorkerManager:
    def __init__(self) -> None:
        self.workers: dict[str, WorkerEntry] = {}
        self._futures: dict[str, asyncio.Future] = {}
        self._session_worker: dict[str, str] = {}
        self._rr_index = 0
        self._lock = asyncio.Lock()
        self._worker_counter = 0

    # ----- Feature 2: VPS-generated worker IDs ------------------------ #
    def _generate_worker_id(self, hostname: str) -> str:
        """Generate unique worker ID on VPS side."""
        self._worker_counter += 1
        return f"worker-{hostname}-{self._worker_counter:03d}"

    # ----- registration ---------------------------------------------- #
    async def register(
        self, ws: WebSocket, hostname: str, max_concurrent: int, accounts: list[str]
    ) -> str:
        worker_id = self._generate_worker_id(hostname)
        async with self._lock:
            self.workers[worker_id] = WorkerEntry(worker_id, ws, max_concurrent, accounts)
        print(f"[vps] worker registered: {worker_id} accounts={accounts}")
        return worker_id

    async def unregister(self, worker_id: str) -> None:
        async with self._lock:
            self.workers.pop(worker_id, None)
            # Clean up session affinity
            to_remove = [k for k, v in self._session_worker.items() if v == worker_id]
            for k in to_remove:
                self._session_worker.pop(k, None)
        print(f"[vps] worker unregistered: {worker_id}")

    # ----- Feature 4: update_accounts runtime ------------------------ #
    async def update_accounts(self, worker_id: str, accounts: list[str]) -> None:
        """Update account list for a worker at runtime."""
        async with self._lock:
            if worker_id in self.workers:
                self.workers[worker_id].accounts = accounts
                print(f"[vps] updated accounts for {worker_id}: {accounts}")

    # ----- Feature 3: Worker wait timeout ---------------------------- #
    async def dispatch(
        self,
        prompt: str,
        mode: str = "new",
        session_id: Optional[str] = None,
        preferred_account: Optional[str] = None,
        **kwargs,
    ) -> dict:
        """Dispatch task with worker wait timeout."""
        # Session affinity for continue mode
        if mode == "continue" and session_id and session_id in self._session_worker:
            worker_id = self._session_worker[session_id]
            if worker_id in self.workers:
                return await self._dispatch_to_worker(
                    worker_id, prompt, mode, session_id, preferred_account, **kwargs
                )

        # Feature 3: Wait for available worker with timeout
        start_wait = time.time()
        while time.time() - start_wait < WORKER_WAIT_TIMEOUT:
            worker_id = await self._pick_worker(preferred_account)
            if worker_id:
                # Store session affinity
                if session_id:
                    self._session_worker[session_id] = worker_id
                return await self._dispatch_to_worker(
                    worker_id, prompt, mode, session_id, preferred_account, **kwargs
                )
            await asyncio.sleep(0.5)

        raise TimeoutError("No available worker within timeout")

    async def _pick_worker(self, preferred_account: Optional[str] = None) -> Optional[str]:
        """Pick least-loaded worker, optionally filtering by account."""
        async with self._lock:
            candidates = [
                w
                for w in self.workers.values()
                if w.in_flight < w.max_concurrent
                and (not preferred_account or preferred_account in w.accounts)
            ]
            if not candidates:
                return None
            # Round-robin among candidates
            self._rr_index = (self._rr_index + 1) % len(candidates)
            return candidates[self._rr_index].worker_id

    async def _dispatch_to_worker(
        self,
        worker_id: str,
        prompt: str,
        mode: str,
        session_id: Optional[str],
        preferred_account: Optional[str],
        **kwargs,
    ) -> dict:
        worker = self.workers.get(worker_id)
        if not worker:
            raise RuntimeError(f"Worker {worker_id} not found")

        task_id = f"task-{uuid.uuid4().hex[:12]}"
        future: asyncio.Future = asyncio.Future()
        self._futures[task_id] = future

        worker.in_flight += 1

        try:
            await worker.ws.send_json(
                {
                    "type": "task",
                    "task_id": task_id,
                    "request": {
                        "prompt": prompt,
                        "mode": mode,
                        "session_id": session_id,
                        "preferred_account": preferred_account,
                        **kwargs,
                    },
                }
            )
            result = await asyncio.wait_for(future, timeout=REQUEST_TIMEOUT)
            return result
        finally:
            worker.in_flight -= 1
            self._futures.pop(task_id, None)

    # ----- result handling ------------------------------------------- #
    async def handle_result(self, msg: dict) -> None:
        task_id = msg.get("task_id")
        if task_id in self._futures:
            self._futures[task_id].set_result(msg.get("result", {}))

    # ----- Feature 13: reject_future on error ------------------------ #
    async def handle_error(self, msg: dict) -> None:
        """Immediately reject future when worker sends error."""
        task_id = msg.get("task_id")
        if task_id in self._futures:
            error_msg = msg.get("error", "Worker error")
            status = msg.get("status", 500)
            # Create HTTPException to propagate status
            exc = HTTPException(status_code=status, detail=error_msg)
            self._futures[task_id].set_exception(exc)

    # ----- Feature 12: Worker stats ---------------------------------- #
    def get_stats(self) -> dict:
        """Get detailed worker statistics."""
        return {
            "total_workers": len(self.workers),
            "workers": [
                {
                    "worker_id": w.worker_id,
                    "accounts": w.accounts,
                    "max_concurrent": w.max_concurrent,
                    "in_flight": w.in_flight,
                    "connected_at": w.connected_at,
                    "uptime_seconds": time.time() - w.connected_at,
                }
                for w in self.workers.values()
            ],
            "total_accounts": sum(len(w.accounts) for w in self.workers.values()),
            "busy_slots": sum(w.in_flight for w in self.workers.values()),
        }

    # ----- Feature 5: List all available accounts -------------------- #
    def list_all_accounts(self) -> list[str]:
        """List all unique accounts across all workers."""
        accounts = set()
        for w in self.workers.values():
            accounts.update(w.accounts)
        return sorted(accounts)


# =========================================================================== #
# FastAPI app
# =========================================================================== #
worker_mgr = WorkerManager()


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield


app = FastAPI(
    title="PAF-ModelDeepSeek Enhanced VPS Bridge",
    description="OpenAI-compatible API for DeepSeek with session persistence & account routing",
    version="2.0.0",
    lifespan=lifespan,
)

# Feature 1: CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure as needed for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =========================================================================== #
# WebSocket endpoint (worker connection)
# =========================================================================== #
@app.websocket("/ws/worker")
async def worker_endpoint(ws: WebSocket):
    await ws.accept()
    worker_id: Optional[str] = None
    try:
        # Registration
        msg = await ws.receive_json()
        if msg.get("type") != "register":
            await ws.close(code=4000, reason="Expected register message")
            return

        token = msg.get("token")
        if token != AUTH_TOKEN:
            await ws.close(code=4001, reason="Invalid token")
            return

        hostname = msg.get("hostname", "unknown")
        max_concurrent = msg.get("max_concurrent", 1)
        accounts = msg.get("accounts", [])

        worker_id = await worker_mgr.register(ws, hostname, max_concurrent, accounts)
        await ws.send_json({"type": "registered", "worker_id": worker_id})

        # Message loop
        async for raw in ws.iter_json():
            mtype = raw.get("type")
            if mtype == "result":
                await worker_mgr.handle_result(raw)
            elif mtype == "error":
                await worker_mgr.handle_error(raw)
            elif mtype == "update_accounts":
                await worker_mgr.update_accounts(worker_id, raw.get("accounts", []))
            elif mtype == "ping":
                # Update last_ping timestamp
                if worker_id in worker_mgr.workers:
                    worker_mgr.workers[worker_id].last_ping = time.time()
                await ws.send_json({"type": "pong"})
            elif mtype == "pong":
                if worker_id in worker_mgr.workers:
                    worker_mgr.workers[worker_id].last_ping = time.time()

    except WebSocketDisconnect:
        pass
    except Exception as e:
        print(f"[vps] worker error: {e}")
    finally:
        if worker_id:
            await worker_mgr.unregister(worker_id)


# =========================================================================== #
# REST API endpoints
# =========================================================================== #
@app.get("/")
async def root():
    """Feature 12: Show detailed worker stats on root."""
    stats = worker_mgr.get_stats()
    return {
        "service": "PAF-ModelDeepSeek Enhanced VPS Bridge",
        "version": "2.0.0",
        "status": "running",
        "workers": stats,
    }


@app.get("/health")
async def health():
    """Feature 12: Detailed health check with worker stats."""
    stats = worker_mgr.get_stats()
    return {
        "status": "healthy" if stats["total_workers"] > 0 else "no_workers",
        "workers": stats,
        "timestamp": time.time(),
    }


@app.get("/v1/models")
async def list_models():
    """List all available accounts (models) registered across all workers."""
    accounts = worker_mgr.list_all_accounts()
    return {
        "object": "list",
        "data": [
            {"id": account_id, "object": "model", "owned_by": "PAF-ai"}
            for account_id in accounts
        ],
    }


@app.post("/v1/chat/completions")
async def chat_completions(request: Request, req: ChatCompletionRequest):
    """Enhanced chat completions with all new features."""
    start_time = time.time()

    try:
        # Feature 8: Resolve think_mode alias
        think_mode_params = _resolve_think_mode(req)
        model_tab = req.model_tab or think_mode_params.get("model_tab")
        deep_think = (
            req.deep_think
            if req.deep_think is not None
            else think_mode_params.get("deep_think", False)
        )
        web_search = (
            req.web_search
            if req.web_search is not None
            else think_mode_params.get("web_search", False)
        )

        # Apply model alias if no explicit model_tab
        if not model_tab:
            alias = MODEL_ALIASES.get(req.model)
            if alias:
                model_tab = alias["model_tab"]
                if req.deep_think is None:
                    deep_think = alias["deep_think"]

        # Default to instant if still None
        model_tab = model_tab or "instant"

        # Generate or use provided session_id
        session_id = req.session_id or f"sess-{uuid.uuid4().hex[:16]}"
        mode = req.mode or "new"

        # Feature 9: Convert attachments to worker format
        attachments = None
        if req.attachments:
            attachments = [
                {
                    "filename": att.filename,
                    "data": att.data,
                    "mime_type": att.mime_type,
                }
                for att in req.attachments
            ]

        # Dispatch to worker
        result = await worker_mgr.dispatch(
            prompt=req.last_user_message(),
            mode=mode,
            session_id=session_id,
            model_tab=model_tab,
            deep_think=deep_think,
            web_search=web_search,
            attachments=attachments,
            preferred_account=req.preferred_account,
        )

        if not result.get("ok"):
            raise HTTPException(status_code=500, detail=result.get("error", "Unknown error"))

        # Build OpenAI-compatible response
        response_text = result.get("text", "")
        prompt_tokens = _token_estimate(req.last_user_message())
        completion_tokens = _token_estimate(response_text)

        # Feature 10: finish_reason and tool_calls support
        finish_reason = "stop"
        tool_calls = None
        if result.get("tool_calls"):
            finish_reason = "tool_calls"
            tool_calls = result["tool_calls"]

        choice = {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": response_text,
            },
            "finish_reason": finish_reason,
        }

        if tool_calls:
            choice["message"]["tool_calls"] = tool_calls

        # Feature 11: x_meta block with extended metadata
        x_meta = {
            "session_id": session_id,
            "account": result.get("account"),
            "conversation_url": result.get("conversation_url"),
            "model_tab": model_tab,
            "deep_think": deep_think,
            "web_search": web_search,
            "response_time": time.time() - start_time,
            "timestamp": time.time(),
        }

        response_data = {
            "id": _make_id(),
            "object": "chat.completion",
            "created": int(time.time()),
            "model": req.model,
            "choices": [choice],
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": prompt_tokens + completion_tokens,
            },
            "x_meta": x_meta,  # Feature 11
        }

        # Feature 6, 7: Add custom headers
        headers = {
            "X-Session-ID": session_id,
        }
        if result.get("account"):
            headers["X-Account-Name"] = result["account"]
        if result.get("conversation_url"):
            headers["X-Conversation-URL"] = result["conversation_url"]

        return JSONResponse(content=response_data, headers=headers)

    except HTTPException:
        raise
    except TimeoutError as e:
        raise HTTPException(status_code=504, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# =========================================================================== #
# Main
# =========================================================================== #
def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="PAF-ModelDeepSeek Enhanced VPS Server")
    p.add_argument("--port", type=int, default=8000, help="Port to listen on")
    p.add_argument("--host", default="0.0.0.0", help="Host to bind to")
    p.add_argument("--token", help="Auth token (overrides PAF_TOKEN env)")
    return p.parse_args()


def main():
    args = _parse_args()
    if args.token:
        global AUTH_TOKEN
        AUTH_TOKEN = args.token

    print(f"[vps] Starting Enhanced VPS Bridge on {args.host}:{args.port}")
    print(f"[vps] Auth token: {AUTH_TOKEN[:8]}***")

    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_level="info",
        access_log=True,
    )


if __name__ == "__main__":
    main()
